version: "1"

services:
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_studies
            MYSQL_USER: tienhg2001
            MYSQL_PASSWORD: tienhg2001
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - backend

networks:
    backend:
        driver: bridge
